### ISSUE TITLE
Editor: Error creating window handle

### ISSUE THREAD

**Issue by ghost** [adventuregamestudio/ags#1027]
Following exception was reported for **AGS 3.5.0.21** by a user on forums:

<pre>
An unexpected error occurred. See below for details.

System.ComponentModel.Win32Exception (0x80004005): Error creating window handle.
   at System.Windows.Forms.NativeWindow.CreateHandle(CreateParams cp)
   at System.Windows.Forms.Control.CreateHandle()
   at System.Windows.Forms.ToolStripDropDown.CreateHandle()
   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.ToolStripManager.ModalMenuFilter.PreFilterMessage(Message& m)
   at System.Windows.Forms.Application.ThreadContext.ProcessFilters(MSG& msg, Boolean& modified)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNati veMethods.IMsoComponent.FPreTranslateMessage(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeN ativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at AGS.Editor.Program.RunApplication(String[] args)
</pre>

_The project was locked. I killed the process and restarted AGS. The project was loaded fine and did compile without problems._

---

Details are vague, unfortunately:

_... i was drawing hotspots, linking them to the local room script and scripting the actions.
Global variables pane was also open in the editor. I remember deleting one variable after first changing all the room scripts (and possibly the global script) were that specific variable was used.
Not sure if also one or more views where also open in the editor at that moment._

**Comment by ivan-mogilko** [comment]
Closing, as the situation is unclear, and similar problem was never reported again.
