### ISSUE TITLE
Characters which name does *not* start with "c" and ends with a number crash dialog styling

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1753]
**Describe the bug**
If there's a character which name
a) does _not_ begin with "c" prefix and
b) ends with a number;
and this character's name is mentioned inside the dialog script, on an indented line (if typing regular script), the Scintilla component crashes during code styling. Following is the exception stack trace:

> System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at ScintillaNET.Scintilla.SetStyling(Int32 length, Int32 style)
   at AGS.Editor.ScintillaWrapper.StyleDialogScript(Int32 linenum, Int32 end)
   at AGS.Editor.ScintillaWrapper.ScintillaControl1_StyleNeeded(Object sender, StyleNeededEventArgs e)
   at ScintillaNET.Scintilla.OnStyleNeeded(StyleNeededEventArgs e)
   at ScintillaNET.Scintilla.WmReflectNotify(Message& m)
   at ScintillaNET.Scintilla.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**AGS Version**
3.6.0

**To Reproduce**
1. Run AGS Editor; create a new game or open an existing one.
2. Create a character called "MyName1".
3. Create a new dialog.
4. Open the dialog for editing, and type this (with spaces or tabs indentation), or copy-paste into the dialog option code:
<pre>  MyName1.Walk(0, 0);</pre>
5. Observe the crash.
6. Sometimes it does not crash immediately; in such case close the game, reopen, and open the previously edited dialog.

**Expected behavior**
No crash.

**Additional context**
This seem to happen only with characters that do not have a "c" prefix. "c" prefix has a special meaning in dialog scripts, as it is checked when converting from character's script name into the "dialog name". How it is related is not immediately clear, and may have to be investigated.

**Comment by ivan-mogilko** [comment]
Apparently, there are two mistakes there.

1) The character dialog names are considered highlighted keywords in dialog script, that's correct. But what is not correct is that the editor tries to highlight them even on indented lines (what would be a regular script).
2) It looks like the crash is happening when the registered keyword has a number on the end, and user types that keyword on an indented line. Normally keywords don't have numbers in them, but character names registered as keyword may do.

**Comment by ivan-mogilko** [comment]
Should be fixed with 436150a90ce6a3c17b4d78c7e0327b722035d49c (also somewhat related 1af911fb43d15476ef58e15ba5216148cdf19a5d)
