### ISSUE TITLE
[AGS4] Unhandled Error in the editor when left clicking on a line in a script.

### ISSUE THREAD

**Issue by tarnos12** [adventuregamestudio/ags#1919]
**Describe the bug**
When left clicking at a line of code the error pops up.
Perhaps it happens only for newly created functions before/right after saving the file.(just a hunch tho)
It happens only for specific lines which seems to be related to a specific function hence the above statement.
It could also be related to my layout:
![d5dfc238b64881be36cc1c5272dd1a53](https://user-images.githubusercontent.com/10388576/218611869-44b979a8-9c9d-4f03-a11b-70a34cb9c1b8.png)

```
Error: InvalidArgument=The value '4' is not a valid value for 'index'.
Parameter name: index
Version: AGS 3.99.101.0

System.ArgumentOutOfRangeException: InvalidArgument=The value '4' is not a valid value for 'index'.
Parameter name: index
    at System.Windows.Forms.ComboBox.ObjectCollection.get_Item(Int32 index)
    at AGS.Editor.ComboBoxCustom.<OnCreateControl>b__4_2(Object s, DrawItemEventArgs a)
    at System.Windows.Forms.DrawItemEventHandler.Invoke(Object sender, DrawItemEventArgs e)
    at System.Windows.Forms.ComboBox.OnDrawItem(DrawItemEventArgs e)
    at System.Windows.Forms.ComboBox.WmReflectDrawItem(Message&m)
    at System.Windows.Forms.ComboBox.WndProc(Message&m)
    at AGS.Editor.ComboBoxCustom.WndProc(Message&m)
    at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message&m)
    at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message&m)
    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**AGS Version**
AGS 4.0
https://cirrus-ci.com/build/5180877416693760

**To Reproduce**
I can't reproduce it.

**Comment by ivan-mogilko** [comment]
Also reproduced in 3.6.0:
#2268

**Comment by AlanDrake** [comment]
I'm still not sure what's going on there, but I expect the problem is happening inside the `DrawItem += (s, a) =>` event inside ComboBoxCustom.

That's where the ineex is being accessed for drawing the item.  I wonder if the event is being added multiple times, or if it's a concurrency issue. Maybe the latter?

**Comment by ericoporto** [comment]
> if it's a concurrency issue

I noticed this lint warning in my VS on the lock:

> S3998: Replace this lock on 'ComboBox' with a lock against an object that cannot be accessed across application domain boundaries. 
>S2445: Do not lock on writable field 'cmbFunctions', use a readonly field instead.

![image](https://github.com/adventuregamestudio/ags/assets/2244442/7d0db309-1848-4f99-8214-831e04046645)

**Comment by ivan-mogilko** [comment]
If you suspect this is a multithreading issue, then reproducing this by hand may be a bad idea. It's better to investigate how the conflict between two threads may occur in theory, and then make some kind of an automatic test that runs operations in a loop very fast, trying to get this conflict happen.
