### ISSUE TITLE
Cannot load demo game after a clean install of AGS 3.3.4

### ISSUE THREAD

**Issue by sonneveld** [adventuregamestudio/ags#268]
Steps to reproduce:
-   Uninstall AGS and delete folder from Program Files
-   Install fresh version of AGS 3.3.4
-   Run AGS and load game.agf from Demo Game/
-   You should see a permission error

Tested on a Windows 7 installation.

Looks like the installer might need to install the demo game in a user accessible directory, or set the permissions inside the installation folder.

Error message:

    ---------------------------
    Adventure Game Studio
    ---------------------------
    An error occurred whilst trying to load your game. The error was: 

    Access to the path 'Speech' is denied.

    If you cannot resolve the error, please post on the AGS Technical Forum for assistance.

    Error details: System.UnauthorizedAccessException: Access to the path 'Speech' is denied.

       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

       at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, DirectorySecurity dirSecurity)

       at System.IO.Directory.CreateDirectory(String path, DirectorySecurity directorySecurity)

       at AGS.Editor.Utilities.EnsureStandardSubFoldersExist()

       at AGS.Editor.Tasks.LoadGameFromDisk(String gameToLoad, Boolean interactive)

       at AGS.Editor.InteractiveTasks.LoadGameFromDisk(String gameToLoad)
    ---------------------------
    OK   
    ---------------------------

**Comment by ivan-mogilko** [comment]
I forgot to close this in time. This was solved with letting user to define custom location to store the Demo Game, having User Documents as default location.

(See a9774418334046f9631c6d14b1d72aa907930487)
