### ISSUE TITLE
Extreme panel dock positions break room editor

### ISSUE THREAD

**Issue by morganwillcock** [adventuregamestudio/ags#620]
If docking the room editor in the left-most, top-most, or bottom-most position (where the content is not listed under a named tab) the room editor will not function correct. The right-most position is typically taken by the project explorer, but has the same issue if you re-arrange panels to put the room editor on the right. 

Two issues have been observed so far:

 - In a similar way to #617 it can cause panel properties for the room objects to be shown in place of properties for other Editor components
 - It can crash when adding and deleting objects (screen capture and trace are below)

![bad_panel](https://user-images.githubusercontent.com/14958747/52593642-5a0c0580-2e41-11e9-80e8-f258cf0abea6.gif)

<pre>Error: Object reference not set to an instance of an object.
Version: AGS 3.4.1.14

System.NullReferenceException: Object reference not set to an instance of an object.
   at AGS.Editor.ObjectsEditorFilter.ContextMenuEventHandler(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)</pre>

**Comment by morganwillcock** [comment]
Here is an example of the properties panel showing properties for the wrong game object.

![bad_panel2](https://user-images.githubusercontent.com/14958747/53133891-d2bf4000-356c-11e9-8c2f-61cc6627c583.gif)

**Comment by ivan-mogilko** [comment]
For the easier reference, I will post my findings here too along with #619.

So far I found that these two problem occur because certain properties, such as ActivePane, or _selectedObject in ObjectsEditorFilter, get changed to something different in the middle of the context menu action. I could not yet find when or why exactly this happens.

For example, you may catch when the Character pane gets wrong properties attached if you go to ContentDocument.SelectedPropertyGridObject setter implementation and put similar check with a break point:
<pre>
                if (value is AGS.Types.Room &&
                    Control.ToString().CompareTo("AGS.Editor.CharacterEditor") == 0)
                {
                    MessageBox.Show("WRONG");
                }
</pre>

This will trigger when you delete room object, the Room pane tries to set "Room" object as ActivePane's SelectedPropertyGridObject, but ActivePane appears to be not Room pane anymore, but Character's pane for some reason.

**Comment by ivan-mogilko** [comment]
This may be related to what TabbedDocumentManager._dockPanel_ActiveContentChanged() is doing.
