### ISSUE TITLE
"Assign sprites to view" crashes the editor

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#918]
1. Have a game with at least 1 sprite and 1 view.
2. Go to the sprite manager, right click on the sprite and select "Assign to view..."
3. Keep default operation settings and press OK.

Observe the crash:

<pre>
Error: Input string was not in a correct format.
Version: AGS 3.5.0.16

System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.Convert.ToInt32(String value)
   at AGS.Editor.SpriteSelector.SpriteContext MenuEventHandler(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.Rais eEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem. OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.Hand leClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.Hand leMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.Fire EventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.Fire Event(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseU p(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown. OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl. WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown. WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNat iveWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNat iveWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callb ack(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
</pre>

**Comment by ivan-mogilko** [comment]
@morganwillcock looks like at some point ListViewItem objects of the sprite selector window stopped using Name property to store sprite number, and instead everywhere program reads their Text to know sprite number instead.
See for example this commit: 92dbbbe6c67290960c1cacaa2db3a9c40de9bc83
Was this intentional?

The above error happens because editor still tries to parse list item's Name property in some cases (which is now empty).

**Comment by ivan-mogilko** [comment]
@morganwillcock would it be okay  (perfomance wise) to have a method that converts list item to sprite number instead, to prevent possible discrepancies in the future?

I mean something like -
<pre>
int ItemToSpriteNum(ListViewItem item)
{
    return Convert.ToInt32(item.Text);
}
</pre>

**Comment by morganwillcock** [comment]
> Was there a good purpose to do this?

I think it was just because there wasn't a clear primary field, and the most minimal constructor sets the 'Text' value only.

The only performance issues were down to how items were added (this was also linked to how the control was updated), so adding the conversion function for a known item should be fine.

**Comment by ivan-mogilko** [comment]
Alright then.
Fixed by b43fd4204f9e7e280839af31ed8beda993db317d, also did c3ea7bb16f397f0dfba408936fd0672b225b8383
